version: 2.1
orbs:
  cypress: cypress-io/cypress@3
  slack: circleci/slack@4.4.4

workflows:
  use-my-orb:
    jobs:
      - slack/on-hold
      - cypress/run:
          name: Running tests under chrome
          start-command: npm run start
          cypress-command: npx cypress run --browser chrome --record
          install-browsers: true
      - cypress/run:
          name: Running tests under firefox
          start-command: npm run start
          cypress-command: npx cypress run --browser firefox --record
          install-browsers: true
