version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          record: true
          name: Running tests under chrome
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
      - cypress/run:
          record: true
          name: Running tests under firefox
          cypress-command: npx cypress run --browser firefox
          install-browsers: true
