version: 2.1
orbs:
  cypress: cypress-io/cypress@3

workflows:
  PLOTLY-TESTS:
    jobs:      
      - cypress/run:
          name: Running tests under chrome
          start-command: npm run start
          cypress-command: npx cypress run --browser chrome --record --key $CYPRESS_RECORD_KEY
          install-browsers: true
      - cypress/run:
          name: Running tests under firefox
          start-command: npm run start
          cypress-command: npx cypress run --browser firefox --record --key $CYPRESS_RECORD_KEY
          install-browsers: true
          
